services:
  v:
    build: ./docker/v/latest
    tty: true
    entrypoint: v
    working_dir: /root/v
    volumes:
      - .:/root/v
    ports:
      - 80:80

  v049:
    build: ./docker/v/0.4.9
    entrypoint: v
    working_dir: /home/alpine/app
    volumes:
      - .:/home/alpine/app

  v048:
    build: ./docker/v/0.4.8
    entrypoint: v
    working_dir: /home/alpine/app
    volumes:
      - .:/home/alpine/app

  npm:
    image: node:23-alpine
    entrypoint: npm
    user: node
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - 5173:5173

  siege:
    image: jstarcher/siege:latest
    entrypoint: siege
    # DCU then docker compose run --service-ports siege --time=30s --concurrent=50 --internet --no-parser v
